# ----------------------------------------------------------------
# Dart Analyzer Options - Performance & Const Focused
# ----------------------------------------------------------------
# This configuration enforces best practices in Dart & Flutter.
# It actively encourages using const, immutables, and clean code.
# Run analysis via:
#   flutter analyze
# ----------------------------------------------------------------

analyzer:
  errors:
    always_specify_types: ignore
    avoid_dynamic_calls: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --------------------------------------
    # Const & immutables
    # --------------------------------------
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_parameters: true

    # --------------------------------------
    # Explicit types & clarity
    # --------------------------------------
    always_specify_types: true

    # --------------------------------------
    # Flutter best practices
    # --------------------------------------
    use_key_in_widget_constructors: true
    avoid_dynamic_calls: true

# ----------------------------------------------------------------
# Notes:
# 1. Suppress specific rules in code with:
#      // ignore: rule_name
#      // ignore_for_file: rule_name
# 2. Full list of Dart lints: https://dart.dev/tools/lints
# ----------------------------------------------------------------
